definitions:
  models.UserModel:
    type: object
host: localhost:8080
info:
  contact: {}
  description: RealWorld 项目后端 API 文档
  title: RealWorld API
  version: "1.0"
paths:
  /api/users/login:
    post:
      consumes:
      - application/json
      description: 接收用户登录信息，验证用户信息并返回token
      parameters:
      - description: 用户登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserModel'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功，返回token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 用户名或密码错误
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - users
  /api/users/register:
    post:
      consumes:
      - application/json
      description: 接收用户信息，将用户信息存储到数据库中完成注册
      parameters:
      - description: 用户注册信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserModel'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功，返回创建的用户信息
          schema:
            $ref: '#/definitions/models.UserModel'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 注册用户
      tags:
      - users
swagger: "2.0"
